#include "cities.h"
#include "Graph.h"

void addLink(Graph g, Location start, Location end, Transport type);

void makeHunterMap(Graph g) {
		//### LAND Connections ###

	//ATHENS
	addLink(g, ATHENS, VALONA, LAND);

	//VALONA
	addLink(g, VALONA, ATHENS, LAND);
	addLink(g, VALONA, SALONICA, LAND);
	addLink(g, VALONA, SOFIA, LAND);
	addLink(g, VALONA, SARAJEVO, LAND);

	//SALONICA
	addLink(g, SALONICA, VALONA, LAND);
	addLink(g, SALONICA, SOFIA, LAND);

	//SOFIA
	addLink(g, SOFIA, VARNA, LAND);
	addLink(g, SOFIA, SALONICA, LAND);
	addLink(g, SOFIA, VALONA, LAND);
	addLink(g, SOFIA, SARAJEVO, LAND);
	addLink(g, SOFIA, BELGRADE, LAND);
	addLink(g, SOFIA, BUCHAREST, LAND);

	//VARNA
	addLink(g, VARNA, SOFIA, LAND);
	addLink(g, VARNA, CONSTANTA, LAND);

	//CONSTANTA
	addLink(g, CONSTANTA, VARNA, LAND);
	addLink(g, CONSTANTA, BUCHAREST, LAND);
	addLink(g, CONSTANTA, GALATZ, LAND);

	//GALATZ
	addLink(g, GALATZ, CONSTANTA, LAND);
	addLink(g, GALATZ, BUCHAREST, LAND);
	addLink(g, GALATZ, KLAUSENBURG, LAND);
	addLink(g, GALATZ, CASTLE_DRACULA, LAND);

	//BUCHAREST
	addLink(g, BUCHAREST, GALATZ, LAND);
	addLink(g, BUCHAREST, CONSTANTA, LAND);
	addLink(g, BUCHAREST, SOFIA, LAND);
	addLink(g, BUCHAREST, BELGRADE, LAND);
	addLink(g, BUCHAREST, KLAUSENBURG, LAND);

	//BELGRADE
	addLink(g, BELGRADE, SARAJEVO, LAND);
	addLink(g, BELGRADE, ST_JOSEPH_AND_ST_MARYS, LAND);
	addLink(g, BELGRADE, SZEGED, LAND);
	addLink(g, BELGRADE, KLAUSENBURG, LAND);
	addLink(g, BELGRADE, BUCHAREST, LAND);
	addLink(g, BELGRADE, SOFIA, LAND);

	//SARAJEVO
	addLink(g, SARAJEVO, VALONA, LAND);
	addLink(g, SARAJEVO, ZAGREB, LAND);
	addLink(g, SARAJEVO, ST_JOSEPH_AND_ST_MARYS, LAND);
	addLink(g, SARAJEVO, BELGRADE, LAND);
	addLink(g, SARAJEVO, SOFIA, LAND);

	//ST_JOSEPH_AND_ST_MARYS
	addLink(g, ST_JOSEPH_AND_ST_MARYS, SARAJEVO, LAND);
	addLink(g, ST_JOSEPH_AND_ST_MARYS, ZAGREB, LAND);
	addLink(g, ST_JOSEPH_AND_ST_MARYS, SZEGED, LAND);
	addLink(g, ST_JOSEPH_AND_ST_MARYS, BELGRADE, LAND);

	//SZEGED
	addLink(g, SZEGED, ST_JOSEPH_AND_ST_MARYS, LAND);
	addLink(g, SZEGED, ZAGREB, LAND);
	addLink(g, SZEGED, BUDAPEST, LAND);
	addLink(g, SZEGED, KLAUSENBURG, LAND);
	addLink(g, SZEGED, BELGRADE, LAND);

	//KLAUSENBURG
	addLink(g, KLAUSENBURG, BELGRADE, LAND);
	addLink(g, KLAUSENBURG, SZEGED, LAND);
	addLink(g, KLAUSENBURG, BUDAPEST, LAND);
	addLink(g, KLAUSENBURG, CASTLE_DRACULA, LAND);
	addLink(g, KLAUSENBURG, GALATZ, LAND);
	addLink(g, KLAUSENBURG, BUCHAREST, LAND);

	//CASTLE_DRACULA
	addLink(g, CASTLE_DRACULA, GALATZ, LAND);
	addLink(g, CASTLE_DRACULA, KLAUSENBURG, LAND);

	//ZAGREB
	addLink(g, ZAGREB, SARAJEVO, LAND);
	addLink(g, ZAGREB, MUNICH, LAND);
	addLink(g, ZAGREB, VIENNA, LAND);
	addLink(g, ZAGREB, BUDAPEST, LAND);
	addLink(g, ZAGREB, SZEGED, LAND);
	addLink(g, ZAGREB, ST_JOSEPH_AND_ST_MARYS, LAND);

	//BUDAPEST
	addLink(g, BUDAPEST, ZAGREB, LAND);
	addLink(g, BUDAPEST, VIENNA, LAND);
	addLink(g, BUDAPEST,KLAUSENBURG, LAND);
	addLink(g, BUDAPEST, SZEGED, LAND);

	//VIENNA
	addLink(g, VIENNA, ZAGREB, LAND);
	addLink(g, VIENNA, MUNICH, LAND);
	addLink(g, VIENNA, PRAGUE, LAND);
	addLink(g, VIENNA, BUDAPEST, LAND);

	//PRAGUE
	addLink(g, PRAGUE, NUREMBURG, LAND);
	addLink(g, PRAGUE, BERLIN, LAND);
	addLink(g, PRAGUE, VIENNA, LAND);

	//BERLIN
	addLink(g, BERLIN, LEIPZIG, LAND);
	addLink(g, BERLIN, HAMBURG, LAND);
	addLink(g, BERLIN, PRAGUE, LAND);

	//LEIPZIG
	addLink(g, LEIPZIG, FRANKFURT, LAND);
	addLink(g, LEIPZIG, COLOGNE, LAND);
	addLink(g, LEIPZIG, HAMBURG, LAND);
	addLink(g, LEIPZIG, BERLIN, LAND);
	addLink(g, LEIPZIG, NUREMBURG, LAND);

	//FRANKFURT
	addLink(g, FRANKFURT, STRASBOURG, LAND);
	addLink(g, FRANKFURT, COLOGNE, LAND);
	addLink(g, FRANKFURT, LEIPZIG, LAND);
	addLink(g, FRANKFURT, NUREMBURG, LAND);

	//NUREMBURG
	addLink(g, NUREMBURG, STRASBOURG, LAND);
	addLink(g, NUREMBURG, FRANKFURT, LAND);
	addLink(g, NUREMBURG, LEIPZIG, LAND);
	addLink(g, NUREMBURG, PRAGUE, LAND);
	addLink(g, NUREMBURG, MUNICH, LAND);

	//MUNICH
	addLink(g, MUNICH, MILAN, LAND);
	addLink(g, MUNICH, ZURICH, LAND);
	addLink(g, MUNICH, STRASBOURG, LAND);
	addLink(g, MUNICH, NUREMBURG, LAND);
	addLink(g, MUNICH, VIENNA, LAND);
	addLink(g, MUNICH, ZAGREB, LAND);
	addLink(g, MUNICH, VENICE, LAND);

	//VENICE
	addLink(g, VENICE, FLORENCE, LAND);
	addLink(g, VENICE, GENOA, LAND);
	addLink(g, VENICE, MILAN, LAND);
	addLink(g, VENICE, MUNICH, LAND);

	//FLORENCE
	addLink(g, FLORENCE, GENOA, LAND);
	addLink(g, FLORENCE, VENICE, LAND);
	addLink(g, FLORENCE, ROME, LAND);

	//ROME
	addLink(g, ROME, FLORENCE, LAND);
	addLink(g, ROME, NAPLES, LAND);
	addLink(g, ROME, BARI, LAND);

	//NAPLES
	addLink(g, NAPLES, ROME, LAND);
	addLink(g, NAPLES, BARI, LAND);

	//BARI
	addLink(g, BARI, NAPLES, LAND);
	addLink(g, BARI, ROME, LAND);

	//GENOA
	addLink(g, GENOA, VENICE, LAND);
	addLink(g, GENOA, FLORENCE, LAND);
	addLink(g, GENOA, MILAN, LAND);
	addLink(g, GENOA, MARSEILLES, LAND);

	//MILAN
	addLink(g, MILAN, GENOA, LAND);
	addLink(g, MILAN, VENICE, LAND);
	addLink(g, MILAN, MARSEILLES, LAND);
	addLink(g, MILAN, ZURICH, LAND);
	addLink(g, MILAN, MUNICH, LAND);

	//ZURICH
	addLink(g, ZURICH, MILAN, LAND);
	addLink(g, ZURICH, MUNICH, LAND);
	addLink(g, ZURICH, GENEVA, LAND);
	addLink(g, ZURICH, MARSEILLES, LAND);
	addLink(g, ZURICH, STRASBOURG, LAND);

	//STRASBOURG
	addLink(g, STRASBOURG, ZURICH, LAND);
	addLink(g, STRASBOURG, MUNICH, LAND);
	addLink(g, STRASBOURG, GENEVA, LAND);
	addLink(g, STRASBOURG, NUREMBURG, LAND);
	addLink(g, STRASBOURG, FRANKFURT, LAND);
	addLink(g, STRASBOURG, COLOGNE, LAND);
	addLink(g, STRASBOURG, BRUSSELS, LAND);
	addLink(g, STRASBOURG, PARIS, LAND);

	//COLOGNE
	addLink(g, COLOGNE, STRASBOURG, LAND);
	addLink(g, COLOGNE, BRUSSELS, LAND);
	addLink(g, COLOGNE, FRANKFURT, LAND);
	addLink(g, COLOGNE, HAMBURG, LAND);
	addLink(g, COLOGNE, AMSTERDAM, LAND);
	addLink(g, COLOGNE, LEIPZIG, LAND);

	//HAMBURG
	addLink(g, HAMBURG, COLOGNE, LAND);
	addLink(g, HAMBURG, BERLIN, LAND);
	addLink(g, HAMBURG, LEIPZIG, LAND);

	//AMSTERDAM
	addLink(g, AMSTERDAM, COLOGNE, LAND);
	addLink(g, AMSTERDAM, BRUSSELS, LAND);

	//BRUSSELS
	addLink(g, BRUSSELS, AMSTERDAM, LAND);
	addLink(g, BRUSSELS, COLOGNE, LAND);
	addLink(g, BRUSSELS, STRASBOURG, LAND);
	addLink(g, BRUSSELS, PARIS, LAND);
	addLink(g, BRUSSELS, LE_HAVRE, LAND);

	//GENEVA
	addLink(g, GENEVA, ZURICH, LAND);
	addLink(g, GENEVA, STRASBOURG, LAND);
	addLink(g, GENEVA, PARIS, LAND);
	addLink(g, GENEVA, CLERMONT_FERRAND, LAND);
	addLink(g, GENEVA, MARSEILLES, LAND);

	//MARSEILLES
	addLink(g, MARSEILLES, GENEVA, LAND);
	addLink(g, MARSEILLES, ZURICH, LAND);
	addLink(g, MARSEILLES, MILAN, LAND);
	addLink(g, MARSEILLES, GENOA, LAND);
	addLink(g, MARSEILLES, CLERMONT_FERRAND, LAND);
	addLink(g, MARSEILLES, TOULOUSE, LAND);

	//CLERMONT_FERRAND
	addLink(g, CLERMONT_FERRAND, MARSEILLES, LAND);
	addLink(g, CLERMONT_FERRAND, GENEVA, LAND);
	addLink(g, CLERMONT_FERRAND, TOULOUSE, LAND);
	addLink(g, CLERMONT_FERRAND, PARIS, LAND);
	addLink(g, CLERMONT_FERRAND, BORDEAUX, LAND);
	addLink(g, CLERMONT_FERRAND, NANTES, LAND);

	//PARIS
	addLink(g, PARIS, STRASBOURG, LAND);
	addLink(g, PARIS, GENEVA, LAND);
	addLink(g, PARIS, BRUSSELS, LAND);
	addLink(g, PARIS, LE_HAVRE, LAND);
	addLink(g, PARIS, NANTES, LAND);
	addLink(g, PARIS, CLERMONT_FERRAND, LAND);

	//LE_HAVRE
	addLink(g, LE_HAVRE, PARIS, LAND);
	addLink(g, LE_HAVRE, BRUSSELS, LAND);
	addLink(g, LE_HAVRE, NANTES, LAND);

	//NANTES
	addLink(g, NANTES, LE_HAVRE, LAND);
	addLink(g, NANTES, PARIS, LAND);
	addLink(g, NANTES, BORDEAUX, LAND);
	addLink(g, NANTES, CLERMONT_FERRAND, LAND);

	//BORDEAUX
	addLink(g, BORDEAUX, NANTES, LAND);
	addLink(g, BORDEAUX, CLERMONT_FERRAND, LAND);
	addLink(g, BORDEAUX, TOULOUSE, LAND);
	addLink(g, BORDEAUX, SARAGOSSA, LAND);

	//TOULOUSE
	addLink(g, TOULOUSE, BORDEAUX, LAND);
	addLink(g, TOULOUSE, CLERMONT_FERRAND, LAND);
	addLink(g, TOULOUSE, MARSEILLES, LAND);
	addLink(g, TOULOUSE, BARCELONA, LAND);
	addLink(g, TOULOUSE, SARAGOSSA, LAND);

	//SARAGOSSA
	addLink(g, SARAGOSSA, TOULOUSE, LAND);
	addLink(g, SARAGOSSA, BARCELONA, LAND);
	addLink(g, SARAGOSSA, BORDEAUX, LAND);
	addLink(g, SARAGOSSA, ALICANTE, LAND);
	addLink(g, SARAGOSSA, MADRID, LAND);
	addLink(g, SARAGOSSA, SANTANDER, LAND);

	//BARCELONA
	addLink(g, BARCELONA, SARAGOSSA, LAND);
	addLink(g, BARCELONA, TOULOUSE, LAND);

	//ALICANTE
	addLink(g, ALICANTE, SARAGOSSA, LAND);
	addLink(g, ALICANTE, GRANADA, LAND);
	addLink(g, ALICANTE, MADRID, LAND);

	//GRANADA
	addLink(g, GRANADA, ALICANTE, LAND);
	addLink(g, GRANADA, MADRID, LAND);
	addLink(g, GRANADA, CADIZ, LAND);

	//CADIZ
	addLink(g, CADIZ, GRANADA, LAND);
	addLink(g, CADIZ, MADRID, LAND);
	addLink(g, CADIZ, LISBON, LAND);

	//LISBON
	addLink(g, LISBON, CADIZ, LAND);
	addLink(g, LISBON, MADRID, LAND);
	addLink(g, LISBON, SANTANDER, LAND);

	//MADRID
	addLink(g, MADRID, LISBON, LAND);
	addLink(g, MADRID, CADIZ, LAND);
	addLink(g, MADRID, GRANADA, LAND);
	addLink(g, MADRID, ALICANTE, LAND);
	addLink(g, MADRID, SANTANDER, LAND);
	addLink(g, MADRID, SARAGOSSA, LAND);

	//SANTANDER
	addLink(g, SANTANDER, MADRID, LAND);
	addLink(g, SANTANDER, LISBON, LAND);
	addLink(g, SANTANDER, SARAGOSSA, LAND);

	//LONDON
	addLink(g, LONDON, PLYMOUTH, LAND);
	addLink(g, LONDON, SWANSEA, LAND);
	addLink(g, LONDON, MANCHESTER, LAND);

	//PLYMOUTH
	addLink(g, PLYMOUTH, LONDON, LAND);

	//SWANSEA
	addLink(g, SWANSEA, LONDON, LAND);
	addLink(g, SWANSEA, LIVERPOOL, LAND);

	//MANCHESTER
	addLink(g, MANCHESTER, LIVERPOOL, LAND);
	addLink(g, MANCHESTER, EDINBURGH, LAND);
	addLink(g, MANCHESTER, LONDON, LAND);

	//LIVERPOOL
	addLink(g, LIVERPOOL, SWANSEA, LAND);
	addLink(g, LIVERPOOL, MANCHESTER, LAND);

	//DUBLIN
	addLink(g, DUBLIN, GALWAY, LAND);

	//GALWAY
	addLink(g, GALWAY, DUBLIN, LAND);

	//EDINBURGH
	addLink(g, EDINBURGH, MANCHESTER, LAND);

	//### RAIL Connections ###

	//ALICANTE
	addLink(g, ALICANTE, MADRID, RAIL);
	addLink(g, ALICANTE, BARCELONA, RAIL);

	//MADRID
	addLink(g, MADRID, ALICANTE, RAIL);
	addLink(g, MADRID, LISBON, RAIL);
	addLink(g, MADRID, SANTANDER, RAIL);
	addLink(g, MADRID, SARAGOSSA, RAIL);

	//BARCELONA
	addLink(g, BARCELONA, ALICANTE, RAIL);
	addLink(g, BARCELONA, SARAGOSSA, RAIL);

	//LISBON
	addLink(g, LISBON, MADRID, RAIL);


	//SANTANDER
	addLink(g, SANTANDER, MADRID, RAIL);

	//SARAGOSSA
	addLink(g, SARAGOSSA, MADRID, RAIL);
	addLink(g, SARAGOSSA, BARCELONA, RAIL);
	addLink(g, SARAGOSSA, BORDEAUX, RAIL);

	//BORDEAUX
	addLink(g, BORDEAUX, SARAGOSSA, RAIL);
	addLink(g, BORDEAUX, PARIS, RAIL);

	//LE_HAVRE
	addLink(g, LE_HAVRE, PARIS, RAIL);

	//MARSEILLES
	addLink(g, MARSEILLES, PARIS, RAIL);

	//PARIS
	addLink(g, PARIS, BORDEAUX, RAIL);
	addLink(g, PARIS, MARSEILLES, RAIL);
	addLink(g, PARIS, LE_HAVRE, RAIL);
	addLink(g, PARIS, BRUSSELS, RAIL);


	//BRUSSELS
	addLink(g, BRUSSELS, COLOGNE, RAIL);
	addLink(g, BRUSSELS, PARIS, RAIL);

	//COLOGNE
	addLink(g, COLOGNE, BRUSSELS, RAIL);
	addLink(g, COLOGNE, FRANKFURT, RAIL);

	//FRANKFURT
	addLink(g, FRANKFURT, STRASBOURG, RAIL);
	addLink(g, FRANKFURT, LEIPZIG, RAIL);
	addLink(g, FRANKFURT, COLOGNE, RAIL);

	//STRASBOURG
	addLink(g, STRASBOURG, FRANKFURT, RAIL);
	addLink(g, STRASBOURG, ZURICH, RAIL);

	//ZURICH
	addLink(g, ZURICH, MILAN, RAIL);
	addLink(g, ZURICH, STRASBOURG, RAIL);

	//GENEVA
	addLink(g, GENEVA, MILAN, RAIL);

	//GEONA
	addLink(g, GENOA, MILAN, RAIL);

	//MILAN
	addLink(g, MILAN, GENEVA, RAIL);
	addLink(g, MILAN, FLORENCE, RAIL);
	addLink(g, MILAN, ZURICH, RAIL);
	addLink(g, MILAN, GENOA, RAIL);

	//FLORENCE
	addLink(g, FLORENCE, ROME, RAIL);
	addLink(g, FLORENCE, MILAN, RAIL);

	//ROME
	addLink(g, ROME, FLORENCE, RAIL);
	addLink(g, ROME, NAPLES, RAIL);

	//NAPLES
	addLink(g, NAPLES, ROME, RAIL);
	addLink(g, NAPLES, BARI, RAIL);

	//BARI
	addLink(g, BARI, NAPLES, RAIL);

	//LEIPZIG
	addLink(g, LEIPZIG, FRANKFURT, RAIL);
	addLink(g, LEIPZIG, NUREMBURG, RAIL);
	addLink(g, LEIPZIG, BERLIN, RAIL);

	//BERLIN
	addLink(g, BERLIN, HAMBURG, RAIL);
	addLink(g, BERLIN, PRAGUE, RAIL);
	addLink(g, BERLIN, LEIPZIG, RAIL);

	//HAMBURG
	addLink(g, HAMBURG, BERLIN, RAIL);

	//MUNICH
	addLink(g, MUNICH, NUREMBURG, RAIL);

	//NUREMBURG
	addLink(g, NUREMBURG, MUNICH, RAIL);
	addLink(g, NUREMBURG, LEIPZIG, RAIL);

	//PRAGUE
	addLink(g, PRAGUE, BERLIN, RAIL);
	addLink(g, PRAGUE, VIENNA, RAIL);

	//VIENNA
	addLink(g, VIENNA, PRAGUE, RAIL);
	addLink(g, VIENNA, VENICE, RAIL);
	addLink(g, VIENNA, BUDAPEST, RAIL);

	//VENICE
	addLink(g, VENICE, VIENNA, RAIL);

	//BUDAPEST
	addLink(g, BUDAPEST, VIENNA, RAIL);
	addLink(g, BUDAPEST, SZEGED, RAIL);

	//SZEGED
	addLink(g, SZEGED, BUDAPEST, RAIL);
	addLink(g, SZEGED, BELGRADE, RAIL);
	addLink(g, SZEGED, BUCHAREST, RAIL);

	//BELGRADE
	addLink(g, BELGRADE, SZEGED, RAIL);
	addLink(g, BELGRADE, SOFIA, RAIL);


	//SOFIA
	addLink(g, SOFIA, BELGRADE, RAIL);
	addLink(g, SOFIA, SALONICA, RAIL);
	addLink(g, SOFIA, VARNA, RAIL);

	//SALONICA
	addLink(g, SALONICA, SOFIA, RAIL);

	//VARNA
	addLink(g, VARNA, SOFIA, RAIL);

	//BUCHAREST
	addLink(g, BUCHAREST, SZEGED, RAIL);
	addLink(g, BUCHAREST, GALATZ, RAIL);
	addLink(g, BUCHAREST, CONSTANTA, RAIL);

	//GALATZ
	addLink(g, GALATZ, BUCHAREST, RAIL);

	//CONSTANTA
	addLink(g, CONSTANTA, BUCHAREST, RAIL);

	//LONDON
	addLink(g, LONDON, SWANSEA, RAIL);
	addLink(g, LONDON, MANCHESTER, RAIL);

	//SWANSEA
	addLink(g, SWANSEA, LONDON, RAIL);

	//MANCHESTER
	addLink(g, MANCHESTER, LONDON, RAIL);
	addLink(g, MANCHESTER, LIVERPOOL, RAIL);
	addLink(g, MANCHESTER, EDINBURGH, RAIL);

	//EDINBURGH
	addLink(g, EDINBURGH, MANCHESTER, RAIL);

	//LIVERPOOL
	addLink(g, LIVERPOOL, MANCHESTER, RAIL);

	//### SEA Connections ###

	//BLACK SEA
	addLink(g, BLACK_SEA, IONIAN_SEA, SEA);
	addLink(g, BLACK_SEA, VARNA, SEA);
	addLink(g, BLACK_SEA, CONSTANTA, SEA);

	//IONIAN SEA
	addLink(g, IONIAN_SEA, BLACK_SEA, SEA);
	addLink(g, IONIAN_SEA, VALONA, SEA);
	addLink(g, IONIAN_SEA, ATHENS, SEA);
	addLink(g, IONIAN_SEA, SALONICA, SEA);
	addLink(g, IONIAN_SEA, ADRIATIC_SEA, SEA);
	addLink(g, IONIAN_SEA, TYRRHENIAN_SEA, SEA);

	//ADRIATIC SEA
	addLink(g, ADRIATIC_SEA, VENICE, SEA);
	addLink(g, ADRIATIC_SEA, BARI, SEA);
	addLink(g, ADRIATIC_SEA, IONIAN_SEA, SEA);

	//TYRRHENIAN SEA
	addLink(g, TYRRHENIAN_SEA, MEDITERRANEAN_SEA, SEA);
	addLink(g, TYRRHENIAN_SEA, CAGLIARI, SEA);
	addLink(g, TYRRHENIAN_SEA, GENOA, SEA);
	addLink(g, TYRRHENIAN_SEA, ROME, SEA);
	addLink(g, TYRRHENIAN_SEA, NAPLES, SEA);
	addLink(g, TYRRHENIAN_SEA, IONIAN_SEA, SEA);

	//MEDITERRANEAN_SEA
	addLink(g, MEDITERRANEAN_SEA, ATLANTIC_OCEAN, SEA);
	addLink(g, MEDITERRANEAN_SEA, TYRRHENIAN_SEA, SEA);
	addLink(g, MEDITERRANEAN_SEA, CAGLIARI, SEA);
	addLink(g, MEDITERRANEAN_SEA, MARSEILLES, SEA);
	addLink(g, MEDITERRANEAN_SEA, BARCELONA, SEA);
	addLink(g, MEDITERRANEAN_SEA, ALICANTE, SEA);

	//BAY_OF_BISCAY
	addLink(g, BAY_OF_BISCAY, ATLANTIC_OCEAN, SEA);
	addLink(g, BAY_OF_BISCAY, BORDEAUX, SEA);
	addLink(g, BAY_OF_BISCAY, SANTANDER, SEA);
	addLink(g, BAY_OF_BISCAY, NANTES, SEA);

	//ATLANTIC_OCEAN
	addLink(g, ATLANTIC_OCEAN, NORTH_SEA, SEA);
	addLink(g, ATLANTIC_OCEAN, BAY_OF_BISCAY, SEA);
	addLink(g, ATLANTIC_OCEAN, IRISH_SEA, SEA);
	addLink(g, ATLANTIC_OCEAN, ENGLISH_CHANNEL, SEA);
	addLink(g, ATLANTIC_OCEAN, MEDITERRANEAN_SEA, SEA);
	addLink(g, ATLANTIC_OCEAN, CADIZ, SEA);
	addLink(g, ATLANTIC_OCEAN, LISBON, SEA);
	addLink(g, ATLANTIC_OCEAN, GALWAY, SEA);

	//ENGLISH_CHANNEL
	addLink(g, ENGLISH_CHANNEL, ATLANTIC_OCEAN, SEA);
	addLink(g, ENGLISH_CHANNEL, NORTH_SEA, SEA);
	addLink(g, ENGLISH_CHANNEL, LE_HAVRE, SEA);
	addLink(g, ENGLISH_CHANNEL, PLYMOUTH, SEA);
	addLink(g, ENGLISH_CHANNEL, LONDON, SEA);

	//IRISH_SEA
	addLink(g, IRISH_SEA, ATLANTIC_OCEAN, SEA);
	addLink(g, IRISH_SEA, LIVERPOOL, SEA);
	addLink(g, IRISH_SEA, SWANSEA, SEA);
	addLink(g, IRISH_SEA, DUBLIN, SEA);

	//NORTH_SEA
	addLink(g, NORTH_SEA, ATLANTIC_OCEAN, SEA);
	addLink(g, NORTH_SEA, ENGLISH_CHANNEL, SEA);
	addLink(g, NORTH_SEA, EDINBURGH, SEA);
	addLink(g, NORTH_SEA, AMSTERDAM, SEA);
	addLink(g, NORTH_SEA, HAMBURG, SEA);

	//### SEA->CITIES Connections ###

	addLink(g, CONSTANTA, BLACK_SEA, SEA);
	addLink(g, VARNA, BLACK_SEA, SEA);
	addLink(g, SALONICA, IONIAN_SEA, SEA);
	addLink(g, ATHENS, IONIAN_SEA, SEA);
	addLink(g, VALONA, IONIAN_SEA, SEA);
	addLink(g, BARI, ADRIATIC_SEA, SEA);
	addLink(g, VENICE, ADRIATIC_SEA, SEA);
	addLink(g, NAPLES, TYRRHENIAN_SEA, SEA);
	addLink(g, ROME, TYRRHENIAN_SEA, SEA);
	addLink(g, GENOA, TYRRHENIAN_SEA, SEA);
	addLink(g, CAGLIARI, TYRRHENIAN_SEA, SEA);
	addLink(g, CAGLIARI, MEDITERRANEAN_SEA, SEA);
	addLink(g, MARSEILLES, MEDITERRANEAN_SEA, SEA);
	addLink(g, BARCELONA, MEDITERRANEAN_SEA, SEA);
	addLink(g, ALICANTE, MEDITERRANEAN_SEA, SEA);
	addLink(g, CADIZ, ATLANTIC_OCEAN, SEA);
	addLink(g, LISBON, ATLANTIC_OCEAN, SEA);
	addLink(g, GALWAY, ATLANTIC_OCEAN, SEA);
	addLink(g, SANTANDER, BAY_OF_BISCAY, SEA);
	addLink(g, BORDEAUX, BAY_OF_BISCAY, SEA);
	addLink(g, NANTES, BAY_OF_BISCAY, SEA);
	addLink(g, LONDON, ENGLISH_CHANNEL, SEA);
	addLink(g, PLYMOUTH, ENGLISH_CHANNEL, SEA);
	addLink(g, LE_HAVRE, ENGLISH_CHANNEL, SEA);
	addLink(g, SWANSEA, IRISH_SEA, SEA);
	addLink(g, LIVERPOOL, IRISH_SEA, SEA);
	addLink(g, DUBLIN, IRISH_SEA, SEA);
	addLink(g, EDINBURGH, NORTH_SEA, SEA);
	addLink(g, AMSTERDAM, NORTH_SEA, SEA);
	addLink(g, HAMBURG, NORTH_SEA, SEA);
}